apiVersion: v1
kind: Service
metadata:
  name: svc-clusterip-rybbit-database
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    {{- include "rybbit.labels" . | nindent 4 }}
spec:
  selector:
    app: rybbit-database
  ports:
    - name: clickhouse
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
