{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rybbit.fullname" . }}
  labels:
    {{- include "rybbit.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  {{- if .Values.ingress.className }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:    
    - hosts:
        - {{ .Values.domain_name }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.domain_name }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: svc-clusterip-rybbit
                port:
                  number: 3001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-clusterip-rybbit
                port:
                  number: 3002
{{- end }}