apiVersion: v1
kind: Service
metadata:
  name: svc-clusterip-rybbit
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    {{- include "rybbit.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "rybbit.fullname" . }}
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80
    - name: backend
      protocol: TCP
      port: 3001
      targetPort: 3001
    - name: client
      protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
